### ISSUE TITLE
'st.session_state has no key "authentication_status". Did you forget to initialize it?

### ISSUE THREAD

**Issue by pabloadmin** [jeremyallencpa/stock_prediction_streamlit#1]
Hi, i tryed to execute your code and get this error:

raise KeyError(_missing_key_error_message(key))

KeyError: 'st.session_state has no key "authentication_status". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization'

Thanks

**Comment by jeremyallencpa** [comment]
Are you running this in Streamlit and entering the correct username and password?

**Comment by pabloadmin** [comment]
I tryed but get this error:

Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 16:30:00) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> streamlit run main.py
  File "<stdin>", line 1
    streamlit run main.py
                ^
SyntaxError: invalid syntax
>>> streamlit run main.py

**Comment by pabloadmin** [comment]
I installed all librarys at spider editor and try to run main.py manually, then recive the first error.

**Comment by jeremyallencpa** [comment]
Looks like it may be an issue with your Python version.

Are you using a virtual environment to run it?

Create the virtual environment using: $ python3 -m venv .venv

Activate it using: $ source .venv/bin/activate

**Comment by jeremyallencpa** [comment]
Also, just curious - how did you find this repo?

**Comment by pabloadmin** [comment]
> 
I use windows, its the same?

**Comment by pabloadmin** [comment]
> Also, just curious - how did you find this repo?

I trader and was looking for LSTM analysis at github, when fond your code. I read the code and wanted to try it.

**Comment by jeremyallencpa** [comment]
> > 
> 
> I use windows, its the same?

Yes it should be the same for Windows. If you just want to run the actual LSTM code you can just run the package stock_predictor.py. This full program is meant to be displayed in Streamlit.
